# Generated by Django 5.2.3 on 2025-06-26 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_subcategory'),
        ('Order', '0002_remove_order_category_order_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Category.subcategory'),
        ),
    ]
