# Generated by Django 5.2.3 on 2025-07-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
        ('Order', '0004_order_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Address.address'),
        ),
    ]
