# Generated by Django 5.2.3 on 2025-06-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
    ]
