# Generated by Django 5.2.3 on 2025-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
