# Generated by Django 5.2.3 on 2025-07-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0010_alter_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
